#python main.py -d data/synthetic.txt -w data/negskewed.txt -a wfspm -t 0.001 >> mem_log.txt
#python main.py -d data/synthetic.txt -w data/negskewed.txt -a wfspm -t 0.0011 >> mem_log.txt
#python main.py -d data/synthetic.txt -w data/negskewed.txt -a wfspm -t 0.0012 >> mem_log.txt
#python main.py -d data/synthetic.txt -w data/negskewed.txt -a wfspm -t 0.0013 >> mem_log.txt
#python main.py -d data/synthetic.txt -w data/negskewed.txt -a wfspm -t 0.0014 >> mem_log.txt
#python main.py -d data/synthetic.txt -w data/negskewed.txt -a wfspm -t 0.0015 >> mem_log.txt
#python main.py -d data/synthetic.txt -w data/negskewed.txt -a wfspm -t 0.0015 >> mem_log.txt
#python main.py -d data/synthetic.txt -w data/negskewed.txt -a wfspm -t 0.0016 >> mem_log.txt
#python main.py -d data/synthetic.txt -w data/negskewed.txt -a wfspm -t 0.0017 >> mem_log.txt
#python main.py -d data/synthetic.txt -w data/negskewed.txt -a wfspm -t 0.0018 >> mem_log.txt
#python main.py -d data/synthetic.txt -w data/negskewed.txt -a wfspm -t 0.0019 >> mem_log.txt
#python main.py -d data/synthetic.txt -w data/negskewed.txt -a wfspm -t 0.0020 >> mem_log.txt
#python main.py -d data/synthetic.txt -w data/negskewed.txt -a wfspm -t 0.0009 >> mem_log.txt
#python main.py -d data/synthetic.txt -w data/negskewed.txt -a wfspm -t 0.0008 >> mem_log.txt
#python main.py -d data/synthetic.txt -w data/negskewed.txt -a wfspm -t 0.0007 >> mem_log.txt
#python main.py -d data/synthetic.txt -w data/negskewed.txt -a wfspm -t 0.0006 >> mem_log.txt
#python main.py -d data/synthetic.txt -w data/negskewed.txt -a wfspm -t 0.0005 >> mem_log.txt
#python main.py -d data/synthetic.txt -w data/negskewed.txt -a iua -t 0.001 >> mem_log.txt
#python main.py -d data/synthetic.txt -w data/negskewed.txt -a iua -t 0.0011 >> mem_log.txt
#python main.py -d data/synthetic.txt -w data/negskewed.txt -a iua -t 0.0012 >> mem_log.txt
#python main.py -d data/synthetic.txt -w data/negskewed.txt -a iua -t 0.0013 >> mem_log.txt
#python main.py -d data/synthetic.txt -w data/negskewed.txt -a iua -t 0.0014 >> mem_log.txt
#python main.py -d data/synthetic.txt -w data/negskewed.txt -a iua -t 0.0015 >> mem_log.txt
#python main.py -d data/synthetic.txt -w data/negskewed.txt -a iua -t 0.0015 >> mem_log.txt
#python main.py -d data/synthetic.txt -w data/negskewed.txt -a iua -t 0.0009 >> mem_log.txt
#python main.py -d data/synthetic.txt -w data/negskewed.txt -a iua -t 0.0008 >> mem_log.txt
#python main.py -d data/synthetic.txt -w data/negskewed.txt -a iua -t 0.0007 >> mem_log.txt
#python main.py -d data/synthetic.txt -w data/negskewed.txt -a iua -t 0.0006 >> mem_log.txt
#python main.py -d data/synthetic.txt -w data/negskewed.txt -a iua -t 0.0005 >> mem_log.txt
#python main.py -d data/kosarak.txt -w data/weight_kosarak.txt -a wfspm -t 0.006 >> mem_log.txt
#Required time is 1369.0124444961548 seconds
#Candidate: 1034 frequent: 1015
#sign_thrs = [0.05, 0.10, 0.15, 0.20, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5]
#python main.py -d data/SIGN.txt -w data/weight_SIGN.txt -a wfspm -t 0.05 >> mem_log.txt
#python main.py -d data/SIGN.txt -w data/weight_SIGN.txt -a wfspm -t 0.10 >> mem_log.txt
#python main.py -d data/SIGN.txt -w data/weight_SIGN.txt -a wfspm -t 0.15 >> mem_log.txt
#python main.py -d data/SIGN.txt -w data/weight_SIGN.txt -a wfspm -t 0.20 >> mem_log.txt
#python main.py -d data/SIGN.txt -w data/weight_SIGN.txt -a wfspm -t 0.25 >> mem_log.txt
#python main.py -d data/SIGN.txt -w data/weight_SIGN.txt -a wfspm -t 0.30 >> mem_log.txt
#python main.py -d data/SIGN.txt -w data/weight_SIGN.txt -a wfspm -t 0.35 >> mem_log.txt
#python main.py -d data/SIGN.txt -w data/weight_SIGN.txt -a wfspm -t 0.40 >> mem_log.txt
#python main.py -d data/SIGN.txt -w data/weight_SIGN.txt -a wfspm -t 0.45 >> mem_log.txt
#python main.py -d data/SIGN.txt -w data/weight_SIGN.txt -a wfspm -t 0.50 >> mem_log.txt
#python main.py -d data/SIGN.txt -w data/weight_SIGN.txt -a iua -t 0.05 >> mem_log.txt
#python main.py -d data/SIGN.txt -w data/weight_SIGN.txt -a iua -t 0.10 >> mem_log.txt
#python main.py -d data/SIGN.txt -w data/weight_SIGN.txt -a iua -t 0.15 >> mem_log.txt
#python main.py -d data/SIGN.txt -w data/weight_SIGN.txt -a iua -t 0.20 >> mem_log.txt
#python main.py -d data/SIGN.txt -w data/weight_SIGN.txt -a iua -t 0.25 >> mem_log.txt
#python main.py -d data/SIGN.txt -w data/weight_SIGN.txt -a iua -t 0.30 >> mem_log.txt
#python main.py -d data/SIGN.txt -w data/weight_SIGN.txt -a iua -t 0.35 >> mem_log.txt
#python main.py -d data/SIGN.txt -w data/weight_SIGN.txt -a iua -t 0.40 >> mem_log.txt
#python main.py -d data/SIGN.txt -w data/weight_SIGN.txt -a iua -t 0.45 >> mem_log.txt
#python main.py -d data/SIGN.txt -w data/weight_SIGN.txt -a iua -t 0.50 >> mem_log.txt
#python main.py -d data/SIGN.txt -w data/weight_SIGN.txt -a wspan -t 0.05 >> mem_log.txt
#python main.py -d data/SIGN.txt -w data/weight_SIGN.txt -a wspan -t 0.10 >> mem_log.txt
#python main.py -d data/SIGN.txt -w data/weight_SIGN.txt -a wspan -t 0.15 >> mem_log.txt
#python main.py -d data/SIGN.txt -w data/weight_SIGN.txt -a wspan -t 0.20 >> mem_log.txt
#python main.py -d data/SIGN.txt -w data/weight_SIGN.txt -a wspan -t 0.25 >> mem_log.txt
#python main.py -d data/SIGN.txt -w data/weight_SIGN.txt -a wspan -t 0.30 >> mem_log.txt
#python main.py -d data/SIGN.txt -w data/weight_SIGN.txt -a wspan -t 0.35 >> mem_log.txt
#python main.py -d data/SIGN.txt -w data/weight_SIGN.txt -a wspan -t 0.40 >> mem_log.txt
#python main.py -d data/SIGN.txt -w data/weight_SIGN.txt -a wspan -t 0.45 >> mem_log.txt
#python main.py -d data/SIGN.txt -w data/weight_SIGN.txt -a wspan -t 0.50 >> mem_log.txt
#python main.py -d data/LEVIATHAN.txt -w data/weight_LEVIATHAN.txt -a wfspm -t 0.01 >> mem_log.txt
#python main.py -d data/LEVIATHAN.txt -w data/weight_LEVIATHAN.txt -a wfspm -t 0.03 >> mem_log.txt
#python main.py -d data/LEVIATHAN.txt -w data/weight_LEVIATHAN.txt -a wfspm -t 0.05 >> mem_log.txt
#python main.py -d data/LEVIATHAN.txt -w data/weight_LEVIATHAN.txt -a wfspm -t 0.07 >> mem_log.txt
#python main.py -d data/LEVIATHAN.txt -w data/weight_LEVIATHAN.txt -a wfspm -t 0.09 >> mem_log.txt
#python main.py -d data/LEVIATHAN.txt -w data/weight_LEVIATHAN.txt -a wfspm -t 0.11 >> mem_log.txt
#python main.py -d data/LEVIATHAN.txt -w data/weight_LEVIATHAN.txt -a wfspm -t 0.13 >> mem_log.txt
#python main.py -d data/LEVIATHAN.txt -w data/weight_LEVIATHAN.txt -a wfspm -t 0.15 >> mem_log.txt
#python main.py -d data/LEVIATHAN.txt -w data/weight_LEVIATHAN.txt -a wfspm -t 0.17 >> mem_log.txt
#python main.py -d data/LEVIATHAN.txt -w data/weight_LEVIATHAN.txt -a wfspm -t 0.19 >> mem_log.txt
#python main.py -d data/LEVIATHAN.txt -w data/weight_LEVIATHAN.txt -a iua -t 0.01 >> mem_log.txt
#python main.py -d data/LEVIATHAN.txt -w data/weight_LEVIATHAN.txt -a iua -t 0.03 >> mem_log.txt
#python main.py -d data/LEVIATHAN.txt -w data/weight_LEVIATHAN.txt -a iua -t 0.05 >> mem_log.txt
#python main.py -d data/LEVIATHAN.txt -w data/weight_LEVIATHAN.txt -a iua -t 0.07 >> mem_log.txt
#python main.py -d data/LEVIATHAN.txt -w data/weight_LEVIATHAN.txt -a iua -t 0.09 >> mem_log.txt
#python main.py -d data/LEVIATHAN.txt -w data/weight_LEVIATHAN.txt -a iua -t 0.11 >> mem_log.txt
#python main.py -d data/LEVIATHAN.txt -w data/weight_LEVIATHAN.txt -a iua -t 0.13 >> mem_log.txt
#python main.py -d data/LEVIATHAN.txt -w data/weight_LEVIATHAN.txt -a iua -t 0.15 >> mem_log.txt
#python main.py -d data/LEVIATHAN.txt -w data/weight_LEVIATHAN.txt -a iua -t 0.17 >> mem_log.txt
#python main.py -d data/LEVIATHAN.txt -w data/weight_LEVIATHAN.txt -a iua -t 0.19 >> mem_log.txt
#python main.py -d data/LEVIATHAN.txt -w data/weight_LEVIATHAN.txt -a wspan -t 0.01 >> mem_log.txt
#python main.py -d data/LEVIATHAN.txt -w data/weight_LEVIATHAN.txt -a wspan -t 0.03 >> mem_log.txt
#python main.py -d data/LEVIATHAN.txt -w data/weight_LEVIATHAN.txt -a wspan -t 0.05 >> mem_log.txt
#python main.py -d data/LEVIATHAN.txt -w data/weight_LEVIATHAN.txt -a wspan -t 0.07 >> mem_log.txt
#python main.py -d data/LEVIATHAN.txt -w data/weight_LEVIATHAN.txt -a wspan -t 0.09 >> mem_log.txt
#python main.py -d data/LEVIATHAN.txt -w data/weight_LEVIATHAN.txt -a wspan -t 0.11 >> mem_log.txt
#python main.py -d data/LEVIATHAN.txt -w data/weight_LEVIATHAN.txt -a wspan -t 0.13 >> mem_log.txt
#python main.py -d data/LEVIATHAN.txt -w data/weight_LEVIATHAN.txt -a wspan -t 0.15 >> mem_log.txt
#python main.py -d data/LEVIATHAN.txt -w data/weight_LEVIATHAN.txt -a wspan -t 0.17 >> mem_log.txt
#python main.py -d data/LEVIATHAN.txt -w data/weight_LEVIATHAN.txt -a wspan -t 0.19 >> mem_log.txt

